"""create follows table

Revision ID: 00a8900dbb77
Revises: fddc693df640
Create Date: 2025-11-26 20:20:27.282982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a8900dbb77'
down_revision: Union[str, Sequence[str], None] = 'fddc693df640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_index('ix_follows_followed_id', 'follows', ['followed_id'], unique=False)
    op.create_index('ix_follows_follower_id', 'follows', ['follower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_follower_id', table_name='follows')
    op.drop_index('ix_follows_followed_id', table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
